### ISSUE TITLE
Angstrom unit broken in the new UI 

### ISSUE THREAD

**Issue by vedina** [ideaconsult/jToxKit#19]
Was displayed correctly in the old UI https://search.data.enanomapper.net/enm/?search=COD1517080

possibly UTF-8 issue

**Comment by thejonan** [comment]
It looks like a server-side issue - I've reviewed the actual request in the Debugger window, also made a manual request with Postman and this is the way the unit is coming from the server in the SUMMARY fields. Still, the Content-Type of the response is UTF-8, so - there should be an import problem.

**Comment by vedina** [comment]
was fixed server side
