### ISSUE TITLE
Download link misplaced in export tab

### ISSUE THREAD

**Issue by vedina** [ideaconsult/jToxKit#20]
The `development`  branch moved the "select output format" to the bottom

![image](https://cloud.githubusercontent.com/assets/211190/23091448/186b3ad6-f5bf-11e6-835a-38f51c038e47.png)

while the previously deployed version has the download  link at the bottom

![image](https://cloud.githubusercontent.com/assets/211190/23091453/24e9f8ce-f5bf-11e6-9b5a-06a0f5377bde.png)

Not sure what is the reason, could be just mistake in merging. Could you please revert it to match the previously deployed version at https://search.data.enanomapper.net/new/index.html ?

**Comment by thejonan** [comment]
Should be fixed. Please verify, @vedina.
