### ISSUE TITLE
Block join queries with whitespace

### ISSUE THREAD

**Issue by vedina** [ideaconsult/jToxKit#21]
```` 
when a child query contains a space you need to wrap it into {!... v=’..’} local parameter,
 or extract it into a separate request parameter and refer to it by {!... v=$ref}...&ref=...&.
````
https://blog.griddynamics.com/searching-grandchildren-and-siblings-with-solr-block-join 

Partially (the other reason is #22)  because of this issue we obtain same results when searching for `zinc oxide` and `oxide` (which is wrong)

https://search.data.enanomapper.net/new/index.html?search=zinc%20oxide
https://search.data.enanomapper.net/new/index.html?search=oxide

There seems to be a better [workaround](https://issues.apache.org/jira/browse/LUCENE-2605), escaping the space with `\`

https://search.data.enanomapper.net/new/index.html?search=zinc%5C%20oxide

**Comment by thejonan** [comment]
Added `escapeNeedle` option in `Texting` skill from [SolrJsX](https://github.com/ideaconsult/SolrJsX) - version 0.15.1.
