### ISSUE TITLE
New tag to be used for per-server configuration

### ISSUE THREAD

**Issue by vedina** [ideaconsult/jToxKit#23]
There is new `dbtag_hss` keyword in each record of `type_s:substance`.  The goal of this tag to serve as a key for predefined set of server specific settings , denoting the database of origin (e.g. ENM; enanomapper; CANANOLAB: caNanoLab; etc). These should be configurable, not hardcoded. A default configuration should be defined as well.

````
{
        "SUMMARY.SIZE_hss":["34.0 nm",
          "140.0 nm"],
        "dbtag_hss":["ENM"],
        "name_hs":"JRC2011 NM-111",
        "publicname_hs":"NM-111",
        "owner_name_hs":"NanoWiki",
        "substanceType_hs":"NPO_1542",
        "s_uuid_hs":"NWKI-4beee533-65e4-364a-adb7-7a520180de61",
        "type_s":"substance",
        "SUMMARY.RESULTS_hss":["P-CHEM.PC_GRANULOMETRY_SECTION",
          "P-CHEM.SPECIFIC_SURFACE_AREA_SECTION",
          "P-CHEM.SURFACE_CHEMISTRY_SECTION"],
        "SUMMARY.REFOWNERS_hss":["NanoWiki"],
        "id":"caac146b-7916-4e5a-bec9-95d15e2e97af",
        "_version_":1559695868501688321},
  {
        "content_hss":["https://cananolab.nci.nih.gov/caNanoLab/#/sample?sampleId=15368204"],
        "dbtag_hss":["CANANOLAB"],
        "name_hs":"DWU_SNU_SU_US-EParkTL2008-01",
        "publicname_hs":"DWU_SNU_SU_US-EParkTL2008-01",
        "owner_name_hs":"10.1016/j.toxlet.2008.06.869",
        "substanceType_hs":"NPO_1541",
        "s_uuid_hs":"CNLB-5bf1894c-76a9-4a75-9a51-d2da8cec9aed",
        "type_s":"substance",
        "SUMMARY.RESULTS_hss":["TOX.BAO_0002993_SECTION",
          "TOX.BAO_0002168_SECTION",
          "TOX.Targeting"],
        "SUMMARY.REFS_hss":["http://iopscience.iop.org/1749-4699/6/1/014010/article/"],
        "SUMMARY.REFOWNERS_hss":["caNanoLab"],
        "id":"8053bef6-117b-4bce-86b4-8cad364cac84",
        "_version_":1559695895231987712},
````

The configuration should specify at least : the URI of the data server and an icon , e.g.

````
"ENM" : {
  "server" : "https://data.enanomapper.net",
 "icon" : "enmlogo.png"
},
"CANANOLAB" : {
  "server" : "https://apps.ideaconsult.net/enmtest",
 "icon" : "anotherlogo.png"
},
....
````

The server URI should be used to construct the links , as well as any AMBIT queries involved.  Note the export functionality will need to talk to more than one AMBIT server.

**Comment by vedina** [comment]
Please proceed with implementation (ASAP)

**Comment by vedina** [comment]
https://phabricator.ideaconsult.net/T114

**Comment by vedina** [comment]
pls add support for icons, defined by the tag

**Comment by vedina** [comment]
icons are fine, but click on the icon always go for the default ambit server; please modify to use the configured one

**Comment by vedina** [comment]
The dbtag functionality is lost with the recent update by @thejonan . Apart from icons, and most important, the links do not point to the right server, e.g. in https://search.data.enanomapper.net/nanoreg2  NanoTest materials links point to nanoreg1 server, which is not correct.  Please take care to fix the regression.

**Comment by vedina** [comment]
looks like `dbs` tag was changed to `tagDbs` in jToxKit, but existing configurations were not updated. With tag update the previous functionality is restored. 

[Click on the icon](https://github.com/ideaconsult/jToxKit/issues/23#issuecomment-318962397) still needs to be fixed

**Comment by thejonan** [comment]
That one should be fixed too.

**Comment by vedina** [comment]
confirmed
