### ISSUE TITLE
Broken links for substances in the selection tab 

### ISSUE THREAD

**Issue by vedina** [ideaconsult/jToxKit#29]
The links (from the icon, material, Study, etc) for a substance in the `Selection` tab are broken

![image](https://cloud.githubusercontent.com/assets/211190/23599875/55a95a92-024c-11e7-9927-fa534320fcb6.png)

The link looks like `https://search.data.enanomapper.net/new/undefined/IUC5-5f313d1f-4129-499c-abbe-ac18642e2471`, which is incorrect, should be to the database. The links in the `Hit list` tab are ok.

**Comment by thejonan** [comment]
It's fixed along with another problem with lookup table setup.
