### ISSUE TITLE
Remove `Create final Matrix`  button from the assessment workflow

### ISSUE THREAD

**Issue by vedina** [ideaconsult/jToxKit#30]
Remove `Create final Matrix`  button from the assessment workflow - the final matrix is just a view over the working matrix, no need to have a button.

**Comment by thejonan** [comment]
IT should be fixed with this commit: https://github.com/thejonan/Toxtree.js/commit/2bc3962ace4801d9021dba6aa3050d0b0c0a2cc9

**Comment by vedina** [comment]
Confirmed fixed
