### ISSUE TITLE
jToxKit versioning 

### ISSUE THREAD

**Issue by vedina** [ideaconsult/jToxKit#32]
Bringing https://github.com/ideaconsult/Toxtree.js/issues/192 here 

> e.g. being able to say this is jToxKit version 3.14 .  , it is used in e.g. https://search.data.enanomapper.net/new/index.html 
> 
> With Java we are using Apache Maven, where the version is specified in the build system (semantic versioning, i.e. 3.0.2). Each release is a different x.y.z (usually incremental in some reasonable manner). Creating releases in GitHub is quite easy and not entirely related. What I mean is supporting versions in the build system and being able to identify the release once the jToxKit.s is included in a page.
> 
> For example we can create a GitHub release from any jToxKit tag, but once a release is downloaded it will not be straightforward to figure out which tag it was, purely from the js code.

Could you please update what is the status now.
@thejonan

**Comment by vedina** [comment]
property in the global jtoxkit (the new one)

**Comment by thejonan** [comment]
The library is built using the `npm` tool (NodeJs package manager), and the value set for the package (using `package.json) is propagated as a property to the main jToxKit object, i.e. `jToxKit.version` is the version string.

**Comment by vedina** [comment]
ok
