### ISSUE TITLE
Study components broken under IE

### ISSUE THREAD

**Issue by vedina** [ideaconsult/jToxKit#34]
[example](https://apps.ideaconsult.net/nanoreg1/substance/NNRG-19cbc9d8-3156-d3bc-d08b-f7095902b34d/study)

![image](https://cloud.githubusercontent.com/assets/211190/26243396/63070676-3c94-11e7-8197-e02777e0b5c3.png)

This is urgent, please investigate the reason.

@thejonan

**Comment by thejonan** [comment]
Unfortunately it works perfectly fine on other three, Mac supported browsers - Chrome, Firefox and Safari, even without a warning in the console. @tmanolov - probably something around the IE's related asSys bug?

**Comment by vedina** [comment]
yes, it does work fine elsewhere

**Comment by vedina** [comment]
@tmanolov thinks it's the `colResizable`  library

**Comment by tmanolov** [comment]
It is fixed. The library is updated to the latest version.

here:
https://github.com/ideaconsult/Toxtree.js/tree/master/tests

You have to use colResizable-1.6.min.js.

**Comment by vedina** [comment]
Thanks, the colResizable issue is solved indeed.

There is however another IE specific  one - try changing to the URL which is marked as broken in IE in `toxstudy.html` 

![image](https://cloud.githubusercontent.com/assets/211190/26310273/ec38c27e-3f08-11e7-92bb-701e3c17e8cc.png)

**Comment by vedina** [comment]
seems the last one  was server side issue,  works now
