### ISSUE TITLE
code using 'startsWith' broken in IE 

### ISSUE THREAD

**Issue by vedina** [ideaconsult/jToxKit#35]
Any jToxKit code using `startsWith` gives this error in IE  (old jToxKit/Toxtree.js in ambit, ketcher, kToxKit)

`Object doesn't support property or method 'startsWith'`

@thejonan

**Comment by thejonan** [comment]
It looks that `startWith` is used only in the old version of jToxKit, correct?

**Comment by vedina** [comment]
yes, but we do use old jToxKit in ambit UI everywhere

**Comment by thejonan** [comment]
Should be fixed in the old repo.

**Comment by vedina** [comment]
confirmed fixed
