### ISSUE TITLE
Export queries containing space are broken

### ISSUE THREAD

**Issue by vedina** [ideaconsult/jToxKit#36]
e.g. export query for [Alamar blue](https://solr.ideaconsult.net/solr/nanoreg_shard1_replica1/select?fq=%7B!parent%20which%3Dtype_s%3Asubstance%20tag%3Dprotocol_tag%7Dguidance_s%3A%22Alamar%20Blue%22&q=%7B!parent%20which%3Dtype_s%3Asubstance%7D&facet=false&echoParams=none&fl=*%2C%5Bchild%20parentFilter%3Dtype_s%3Asubstance%20childFilter%3D%22guidance_s%3A%22Alamar%20Blue%22%20OR%20type_s%3Acomposition%22%20limit%3D10000%5D&rows=999999&wt=json)

```json
{
"responseHeader": {
"zkConnected": true,
"status": 400,
"QTime": 91
},
"error": {
"metadata": [
"error-class",
"org.apache.solr.common.SolrException",
"root-error-class",
"org.apache.solr.search.SyntaxError"
],
"msg": "Error parsing fieldname",
"code": 400
}
}
```

**Comment by thejonan** [comment]
Should be fixed.

**Comment by vedina** [comment]
confirmed
