### ISSUE TITLE
Toggle and/or for SOLR search via UI

### ISSUE THREAD

**Issue by vedina** [ideaconsult/jToxKit#37]
UI element to switch between `and` and `or` mode to combine SOLR queries

**Comment by thejonan** [comment]
- Add additional UI element
- The persistency of the setting can go in the URL, so it stays between Reloads.

**Comment by thejonan** [comment]
A button next to the search field (in every Tag block) is added with the text `OR` | `AND` stating the current situation with the filter and providing the ability to change it.

The pivot-based tags are not capable of such switching, because re-entering of values is much more complicated.

**Comment by thejonan** [comment]
Added is values / ui persistency - the tags selected are serialized to the URL as well the AND/OR setup. As a result sending an URL to another person should yield exactly the same results.

**Comment by vedina** [comment]
Could you point to example /doc how to activate this  button.

**Comment by thejonan** [comment]
It should be activated, but as you're asking - it's probably hidden too well. It is next to the in-tag block search field (not the general filter filter). This field is scrolled up, by default, if you remember. So you need to open a tag block and either press the small search icon, or scroll up a bit. Let me know if there is still a problem. I'm attaching a screenshot.

<img width="302" alt="screen shot 2017-10-06 at 18 03 05" src="https://user-images.githubusercontent.com/2169351/31284259-ad102dd4-aac0-11e7-9dc7-41feb3511b59.png">

**Comment by vedina** [comment]
confirmed working
