### ISSUE TITLE
Search page Error handling

### ISSUE THREAD

**Issue by vedina** [ideaconsult/jToxKit#38]
initial implementation by @tmanolov as described in https://phabricator.ideaconsult.net/T158 . It shows an alert box for notification of an error,  which needs to be improved.  Would be best if the logging widget as implemented in https://github.com/ideaconsult/Toxtree.js is used instead.

**Comment by thejonan** [comment]
- Attempt to migrate the Logging widget from the old jToxKit.

**Comment by thejonan** [comment]
A whole new kit `jT.ui.Logging` is added and integrated. A fix on missing search results is also implemented.

**Comment by vedina** [comment]
conformed working.
thanks!
