### ISSUE TITLE
Rationale field in assessment workflow-collect structures

### ISSUE THREAD

**Issue by vedina** [ideaconsult/jToxKit#41]
Rationale cannot be given under tab “collect structures”. It can be only given under “list collected”

```
Uncaught TypeError: Cannot read property 'tag' of undefined
    at HTMLTextAreaElement.<anonymous> (ui-matrix.js:792)
    at HTMLTextAreaElement.dispatch (jquery-1.10.2.js:5095)
    at HTMLTextAreaElement.elemData.handle (jquery-1.10.2.js:4766)
colResizable-1.6.min.js:2 Uncaught TypeError: a[A] is not a function
    at colResizable-1.6.min.js:2
    at dispatch (jquery-1.10.2.js:5095)
    at elemData.handle (jquery-1.10.2.js:4766)
```

[More details T170](https://phabricator.ideaconsult.net/T170) @tmanolov

**Comment by thejonan** [comment]
It could be fixed with this commit: https://github.com/thejonan/Toxtree.js/commit/c22d5a7d147b4637c45b6c9d0ab2fb0109002c38

Not tested, though.

**Comment by vedina** [comment]
Not fixed, [see comments](https://phabricator.ideaconsult.net/T170#5353)

**Comment by vedina** [comment]
OK, it needed both your client side fix and a server fix.  Please merge with master
