### ISSUE TITLE
facet UI bug

### ISSUE THREAD

**Issue by vedina** [ideaconsult/jToxKit#42]
When selecting `COMET FPG` it is greyed out, but also `COMET` is greyed out. 
![image](https://user-images.githubusercontent.com/211190/35521304-13322b92-0522-11e8-82a5-be21170fb877.png) [example](https://search.data.enanomapper.net/nanoreg/?&ui=%257B%2522owner_name%2522%253A%257B%2522values%2522%253A%255B%255D%257D%252C%2522reference_owner%2522%253A%257B%2522values%2522%253A%255B%255D%257D%252C%2522substanceType%2522%253A%257B%2522values%2522%253A%255B%255D%257D%252C%2522nm_name%2522%253A%257B%2522values%2522%253A%255B%255D%257D%252C%2522protocol%2522%253A%257B%2522values%2522%253A%255B%255D%257D%252C%2522method%2522%253A%257B%2522values%2522%253A%255B%2522COMET%2520FPG%2522%255D%257D%252C%2522cell%2522%253A%257B%2522values%2522%253A%255B%255D%257D%252C%2522species%2522%253A%257B%2522values%2522%253A%255B%255D%257D%252C%2522route%2522%253A%257B%2522values%2522%253A%255B%255D%257D%252C%2522interpretation%2522%253A%257B%2522values%2522%253A%255B%255D%257D%252C%2522dprotocol%2522%253A%257B%2522values%2522%253A%255B%255D%257D%252C%2522reference_year%2522%253A%257B%2522values%2522%253A%255B%255D%257D%252C%2522reference%2522%253A%257B%2522values%2522%253A%255B%255D%257D%252C%2522release%2522%253A%257B%2522values%2522%253A%255B%255D%257D%257D)

The export results (correctly) contain `COMET FPG` only

**Comment by vedina** [comment]
still valid

**Comment by thejonan** [comment]
This one, actually lies in the SolrJsX library, so it is resolved here: https://github.com/ideaconsult/SolrJsX/pull/20
